buildscript {
    repositories {
        flatDir{
            dirs 'lib'
        }
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
        maven {
        name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }
        maven {
        url "https://cursemaven.com/"
    }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
        runtime 'curse.maven:NarutoMod-1.12.2-0.3.1.beta-831157:5967126'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.0"
group = "com.yourname.modid"
archivesBaseName = "modid"

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = '1.12.2-14.23.5.2855'
    runDir = 'run'
    mappings = 'snapshot_20171003'
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

runClient.outputs.upToDateWhen { false }
runServer.outputs.upToDateWhen { false }

apply from: 'mcreator.gradle'

